# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZH4XZiuXp0eXPmWKvOyWamD3Dp9eGLN9
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y


def divide(x, y):
    if y == 0:
        return "Cannot divide by zero"
    return x / y


def main():
    while True:
        print("Options:")
        print("Enter '1' for addition")
        print("Enter '2' for subtraction")
        print("Enter '3' for multiplication")
        print("Enter '4' for division")
        print("Enter '5' to end the program")

        user_input = input(": ")

        if user_input == "exit":
            break

        if user_input in ("1","2","3","4","5"):
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))

            if user_input == "1":
                print("Result:", add(num1, num2))
            elif user_input == "2":
                print("Result:", subtract(num1, num2))
            elif user_input == "3":
                print("Result:", multiply(num1, num2))
            elif user_input == "4":
                print("Result:", divide(num1, num2))
        else:
            print("Invalid input. Please enter a valid option.")

if __name__ == "__main__":
    main()